#!/bin/sh

case $BLOCK_BUTTON in
    1) konsole -e nmtui ;;
    3) notify-send "Wifi" "LC - открыть nmtui\nRC - вывести это сообщение" ;;
esac
echo "<span bgcolor='#00b894' color='#f3f3f3'> WIFI: `iwgetid -r` </span>"
exit
